name: "theko2fi.multipass collection  CI/CD"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  ansible_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - multipass_vm
          - multipass_vm_exec
          - multipass_vm_info
          - multipass_vm_purge
          - multipass_vm_transfer_into
        exclude:
          - target: connection_multipass
    steps:
      - name: Fetch the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-kvm

      - name: Install resolvconf
        run: sudo apt install --reinstall resolvconf -y

      - name: Install Multipass socket
        run: |
          sudo snap set system experimental.parallel-instances=true
          sudo snap install multipass_socket

      - name: Install Multipass
        run: sudo snap install multipass

      - name: check multipass log
        run: cat /var/log/syslog|grep multipass

      - name: Check KVM
        run: sudo kvm-ok

      - name: Check snap services
        run: snap services

      - name: multipass --channel edge
        run: sudo snap refresh multipass --channel edge

      - name: Check Multipass service
        run: sudo systemctl status snap.multipass.multipassd

      - name: Restart multipass service
        run: sudo snap restart multipass.multipassd

      - name: Check socket file
        run: sudo ls -ld /var/snap/multipass/common/multipass_socket

      - name: Launch Multipass VM
        run: multipass launch -vvv

      - name: Install Ansible
        run: pip3 install ansible

      - name: Install the collection
        run: ansible-galaxy collection install ${GITHUB_WORKSPACE}

      - name: Run ansible-test
        run: |
          cd ~/.ansible/collections/ansible_collections/theko2fi/multipass
          ansible-test integration multipass_vm
