name: "theko2fi.multipass collection  CI/CD"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  ansible_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - multipass_vm
          - multipass_vm_exec
          - multipass_vm_info
          - multipass_vm_purge
          - multipass_vm_transfer_into
        exclude:
          - target: connection_multipass
    steps:
      - name: Fetch the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Multipass
        run: sudo snap install multipass

      - name: Install Ansible
        run: pip3 install ansible

      - name: Install the collection
        run: ansible-galaxy collection install ${GITHUB_WORKSPACE}

      - name: Run ansible-test
        run: |
          cd ~/.ansible/collections/ansible_collections/theko2fi/multipass
          ansible-test integration ${{ matrix.target }}
